task :default => :build

task :build => [:check_clang, :create_output_dir] do
  sh "clang++ src/test/main.cpp -o bin/output/output"
end

task :check_clang do
  sh "clang++ --version"
  unless $?.success?
    puts "x clang not found"
    exit(1)
  else
    puts "✓ clang found"
  end
end

task :create_output_dir do
  mkdir_p "bin/output"
end
