task :default => :build

task :build => [:check_clang, :verify_dependencies] do
  sh "clang++ src/test/main.cpp -o bin/output/output"
end

task :check_clang do
  sh "clang++ --version"
  unless $?.success?
    puts "x clang not found"
    exit(1)
  else
    puts "✓ clang found"
  end
end

task :verify_dependencies do
  sh "./verify.sh"
  unless $?.success?
    puts "x verification failed"
    exit(1)
  else
    puts "✓ verification succeeded"
  end
end
